remote_theme: samarsault/texture

texture:
  title: Allison Letts
  tagline: Learn With Me
  date_format: "%b %-d, %Y"
  style: purple
  showNav: true


  social_links:
    github:  allisonletts
    linkedIn: in/allisonletts # format: locale/username
    
    
