remote_theme: samarsault/texture

texture:
  title: Adam Denisov
  tagline: Developer. Designer
  date_format: "%b %-d, %Y"
  style: purple
  showNav: true


  social_links:
    github:  allisonletts
    linkedIn: in/allisonletts # format: locale/username
    
    
